before_install:
  - psql --version
  - sudo service postgresql stop
  - sudo apt-get -y --purge remove postgresql libpq-dev libpq5 postgresql-client-common postgresql-common
  - sudo rm -rf /var/lib/postgresql
  - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  - sudo sh -c "echo deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main $PGVERSION >> /etc/apt/sources.list.d/postgresql.list"
  - sudo apt-get update -qq
  - sudo apt-get -y install bc libpam-dev libedit-dev
  - sudo apt-get -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::="--force-confnew" install postgresql-$PGVERSION postgresql-server-dev-$PGVERSION postgresql-contrib-$PGVERSION
  - sudo service postgresql stop
  - mkdir pg_data
  - mkdir pg_data/archivelog
  - initdb --no-locale -D pg_data/$PGVERSION
  - chmod 777 /var/run/postgresql
  - sudo echo "local   all         postgres                          trust" > pg_data/$PGVERSION/pg_hba.conf
  - sudo echo "local   all         all                               trust" >> pg_data/$PGVERSION/pg_hba.conf
  - sudo echo "host    all         all         127.0.0.1/32          trust" >> pg_data/$PGVERSION/pg_hba.conf
  - sudo echo "host    all         all         ::1/128               trust" >> pg_data/$PGVERSION/pg_hba.conf
  - sudo echo "logging_collector = on" >> pg_data/$PGVERSION/postgresql.conf
  - sudo echo "wal_level = hot_standby" >> pg_data/$PGVERSION/postgresql.conf
  - sudo echo "archive_mode = on" >> pg_data/$PGVERSION/postgresql.conf
  - sudo echo "archive_command = 'cp %p /var/lib/postgresql/archivelog/%f'" >> pg_data/$PGVERSION/postgresql.conf
  - pg_ctl -D pg_data/$PGVERSION start

before_script:
  - git clone https://github.com/bwtakacy/pg_rman.git pg_rman
  - cd pg_rman && git describe --alway
  - make
  - sudo make install
  - echo 'export PATH=$PATH:/usr/lib/postgresql/$PGVERSION/bin' >> ~/.bashrc
  - export PATH=$PATH:/usr/lib/postgresql/$PGVERSION/bin

env:
  matrix:
    - PGVERSION=9.4
    - PGVERSION=9.3

language: cpp
compiler:
#  - clang
  - gcc

script: make installcheck

after_script:
  - cat /home/travis/build/bwtakacy/pg_rman/pg_rman/regression.diffs
