before_install:
  - psql --version
  - sudo service postgresql stop
  - sudo apt-get -y --purge remove postgresql libpq-dev libpq5 postgresql-client-common postgresql-common
  - sudo rm -rf /var/lib/postgresql
  - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  - sudo sh -c "echo deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main $PGVERSION >> /etc/apt/sources.list.d/postgresql.list"
  - sudo apt-get update -qq
  - sudo apt-get -y install libpam-dev libedit-dev
  - sudo apt-get -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::="--force-confnew" install postgresql-$PGVERSION postgresql-server-dev-$PGVERSION
  - sudo chmod 777 /etc/postgresql/$PGVERSION/main/pg_hba.conf
  - sudo echo "local   all         postgres                          trust" > /etc/postgresql/$PGVERSION/main/pg_hba.conf
  - sudo echo "local   all         all                               trust" >> /etc/postgresql/$PGVERSION/main/pg_hba.conf
  - sudo echo "host    all         all         127.0.0.1/32          trust" >> /etc/postgresql/$PGVERSION/main/pg_hba.conf
  - sudo echo "host    all         all         ::1/128               trust" >> /etc/postgresql/$PGVERSION/main/pg_hba.conf
  - sudo mkdir -p /var/lib/postgresql/archivelog
  - sudo chown postgres:postgres /var/lib/postgresql/archivelog
  - sudo chmod 777 /etc/postgresql/$PGVERSION/main/postgresql.conf
  - sudo echo "logging_collector = on" >> /etc/postgresql/$PGVERSION/main/postgresql.conf
  - sudo echo "wal_level = hot_standby" >> /etc/postgresql/$PGVERSION/main/postgresql.conf
  - sudo echo "archive_mode = on" >> /etc/postgresql/$PGVERSION/main/postgresql.conf
  - sudo echo "archive_command = cp %p /var/lib/postgresql/archivelog/%f" >> /etc/postgresql/$PGVERSION/main/postgresql.conf
  - sudo /etc/init.d/postgresql restart

before_script:
  - git clone https://github.com/bwtakacy/pg_rman.git pg_rman
  - cd pg_rman && git describe --alway
  - make
  - sudo make install

env:
  matrix:
    - PGVERSION=9.4
    - PGVERSION=9.3
    - PGVERSION=9.2

language: cpp
compiler:
#  - clang
  - gcc

script: make installcheck

